// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from "storyblok";
export interface CAppointmentStoryblok {
  headline?: string;
  description?: string;
  teaser: CTeaserItemStoryblok[];
  component: "c-appointment";
  _uid: string;
  [k: string]: any;
}

export type MultilinkStoryblok =
  | {
      fieldtype: "multilink";
      id: string;
      url: string;
      cached_url: string;
      target?: "_blank" | "_self";
      anchor?: string;
      rel?: string;
      title?: string;
      prep?: string;
      linktype: "story";
      story?: {
        name: string;
        created_at?: string;
        published_at?: string;
        id: number;
        uuid: string;
        content?: {
          [k: string]: any;
        };
        slug: string;
        full_slug: string;
        sort_by_date?: null | string;
        position?: number;
        tag_list?: string[];
        is_startpage?: boolean;
        parent_id?: null | number;
        meta_data?: null | {
          [k: string]: any;
        };
        group_id?: string;
        first_published_at?: string;
        release_id?: null | number;
        lang?: string;
        path?: null | string;
        alternates?: any[];
        default_full_slug?: null | string;
        translated_slugs?: null | any[];
        [k: string]: any;
      };
      [k: string]: any;
    }
  | {
      fieldtype: "multilink";
      id: string;
      url: string;
      cached_url: string;
      target?: "_blank" | "_self";
      linktype: "url";
      rel?: string;
      title?: string;
      [k: string]: any;
    }
  | {
      fieldtype: "multilink";
      id: string;
      url: string;
      cached_url: string;
      target?: "_blank" | "_self";
      email?: string;
      linktype: "email";
      [k: string]: any;
    }
  | {
      fieldtype: "multilink";
      id: string;
      url: string;
      cached_url: string;
      target?: "_blank" | "_self";
      linktype: "asset";
      [k: string]: any;
    };

export interface CBlogPostsStoryblok {
  title?: string;
  link?: Exclude<MultilinkStoryblok, {linktype?: "email"} | {linktype?: "asset"}>;
  label?: string;
  limit: string;
  categories?: (number | string)[];
  posts?: (ISbStoryData<TypeBlogStoryblok> | string)[];
  component: "c-blog-posts";
  _uid: string;
  [k: string]: any;
}

export interface CCallToActionStoryblok {
  headline: string;
  description?: string;
  label?: string;
  link?: Exclude<MultilinkStoryblok, {linktype?: "email"} | {linktype?: "asset"}>;
  icon_left?: string;
  icon_right?: string;
  component: "c-call-to-action";
  _uid: string;
  [k: string]: any;
}

export interface CCarouselStoryblok {
  slides: CCarouselSlideStoryblok[];
  component: "c-carousel";
  _uid: string;
  [k: string]: any;
}

export interface AssetStoryblok {
  alt: string | null;
  copyright?: string | null;
  fieldtype: "asset";
  id: number;
  filename: string | null;
  name: string;
  title: string | null;
  focus: string | null;
  meta_data?: {
    [k: string]: any;
  };
  source?: string | null;
  is_external_url?: boolean;
  is_private?: boolean;
  src?: string;
  updated_at?: string;
  width?: number | null;
  height?: number | null;
  aspect_ratio?: number | null;
  public_id?: string | null;
  content_type?: string;
  [k: string]: any;
}

export interface CCarouselSlideStoryblok {
  headline: string;
  description?: string;
  background_image?: AssetStoryblok;
  image?: AssetStoryblok;
  label?: string;
  link?: Exclude<MultilinkStoryblok, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "c-carousel-slide";
  _uid: string;
  [k: string]: any;
}

export interface CFeatureStoryblok {
  margin?: boolean;
  features: CFeatureItemStoryblok[];
  component: "c-feature";
  _uid: string;
  [k: string]: any;
}

export interface RichtextStoryblok {
  type: string;
  content?: RichtextStoryblok[];
  marks?: RichtextStoryblok[];
  attrs?: any;
  text?: string;
  [k: string]: any;
}

export interface CFeatureItemStoryblok {
  icon: string;
  text: RichtextStoryblok;
  component: "c-feature-item";
  _uid: string;
  [k: string]: any;
}

export type MultiassetStoryblok = {
  alt: string | null;
  copyright?: string | null;
  fieldtype: "asset";
  id: number;
  filename: string | null;
  name: string;
  title: string | null;
  focus: string | null;
  meta_data?: {
    [k: string]: any;
  };
  source?: string | null;
  is_external_url?: boolean;
  is_private?: boolean;
  src?: string;
  updated_at?: string;
  width?: number | null;
  height?: number | null;
  aspect_ratio?: number | null;
  public_id?: string | null;
  content_type?: string;
  [k: string]: any;
}[];

export interface CGalleryStoryblok {
  columns: string;
  images: MultiassetStoryblok;
  component: "c-gallery";
  _uid: string;
  [k: string]: any;
}

export interface CGridStoryblok {
  columnCount: string;
  columns?: (CImageStoryblok | CTextStoryblok)[];
  component: "c-grid";
  _uid: string;
  [k: string]: any;
}

export interface CHeadlineStoryblok {
  primary?: boolean;
  headline_type: number | string;
  title: string;
  component: "c-headline";
  _uid: string;
  [k: string]: any;
}

export interface CIconTeaserItemStoryblok {
  icon: string;
  headline: string;
  description?: string;
  link?: Exclude<MultilinkStoryblok, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "c-icon-teaser-item";
  _uid: string;
  [k: string]: any;
}

export interface CIconTeaserItemSmallStoryblok {
  icon: string;
  headline: string;
  component: "c-icon-teaser-item-small";
  _uid: string;
  [k: string]: any;
}

export interface CImageStoryblok {
  half_width?: boolean;
  image: AssetStoryblok;
  component: "c-image";
  _uid: string;
  [k: string]: any;
}

export interface CNewestProductsStoryblok {
  title?: string;
  link?: Exclude<MultilinkStoryblok, {linktype?: "email"} | {linktype?: "asset"}>;
  label?: string;
  limit: string;
  component: "c-newest-products";
  _uid: string;
  [k: string]: any;
}

export interface ConfigurationStoryblok {
  footer_columns: FooterColumnStoryblok[];
  footer_links?: MenuItemStoryblok[];
  notice?: RichtextStoryblok;
  teaser_group?: any;
  teaser_headline?: string;
  teaser?: CIconTeaserItemStoryblok[];
  payment_group?: any;
  payment_headline?: string;
  payment?: CIconTeaserItemSmallStoryblok[];
  partner_group?: any;
  partner_headline?: string;
  partner?: CIconTeaserItemSmallStoryblok[];
  topnavigation?: MenuItemStoryblok[];
  topbar_usps?: UspEntryStoryblok[];
  about_navigation: string;
  service_navigation: string;
  component: "configuration";
  _uid: string;
  [k: string]: any;
}

export interface ConfigurationBlogStoryblok {
  blog_tag_page?: any;
  image: AssetStoryblok;
  title: string;
  additional_title?: string;
  component: "configuration_blog";
  _uid: string;
  [k: string]: any;
}

export interface CPopularCategoriesStoryblok {
  title?: string;
  component: "c-popular-categories";
  _uid: string;
  [k: string]: any;
}

export interface CPortraitTeaserStoryblok {
  title?: string;
  link?: Exclude<MultilinkStoryblok, {linktype?: "email"} | {linktype?: "asset"}>;
  label?: string;
  teaser: CPortraitTeaserItemStoryblok[];
  component: "c-portrait-teaser";
  _uid: string;
  [k: string]: any;
}

export interface CPortraitTeaserItemStoryblok {
  headline: string;
  image: AssetStoryblok;
  link?: Exclude<MultilinkStoryblok, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "c-portrait-teaser-item";
  _uid: string;
  [k: string]: any;
}

export interface CSingleProductStoryblok {
  component: "c-single-product";
  _uid: string;
  [k: string]: any;
}

export interface TableStoryblok {
  thead: {
    _uid: string;
    value?: string;
    component: number;
    [k: string]: any;
  }[];
  tbody: {
    _uid: string;
    body: {
      _uid?: string;
      value?: string;
      component?: number;
      [k: string]: any;
    }[];
    component: number;
    [k: string]: any;
  }[];
  [k: string]: any;
}

export interface CTableStoryblok {
  first_column_bold?: boolean;
  table?: TableStoryblok;
  component: "c-table";
  _uid: string;
  [k: string]: any;
}

export interface CTeaserStoryblok {
  full_width?: boolean;
  gap?: boolean;
  headline?: string;
  description?: string;
  teaser: CTeaserItemStoryblok[];
  component: "c-teaser";
  _uid: string;
  [k: string]: any;
}

export interface CTeaserItemStoryblok {
  headline: string;
  description?: string;
  image: AssetStoryblok;
  label?: string;
  link?: Exclude<MultilinkStoryblok, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "c-teaser-item";
  _uid: string;
  [k: string]: any;
}

export interface CTextStoryblok {
  text: RichtextStoryblok;
  component: "c-text";
  _uid: string;
  [k: string]: any;
}

export interface CTopBrandsStoryblok {
  title?: string;
  link?: Exclude<MultilinkStoryblok, {linktype?: "email"} | {linktype?: "asset"}>;
  label?: string;
  component: "c-top-brands";
  _uid: string;
  [k: string]: any;
}

export interface CTopSellerStoryblok {
  title?: string;
  link?: Exclude<MultilinkStoryblok, {linktype?: "email"} | {linktype?: "asset"}>;
  label?: string;
  limit: string;
  component: "c-top-seller";
  _uid: string;
  [k: string]: any;
}

export interface CVideoStoryblok {
  youtube_id: string;
  component: "c-video";
  _uid: string;
  [k: string]: any;
}

export interface CWikiListingStoryblok {
  component: "c-wiki-listing";
  _uid: string;
  [k: string]: any;
}

export interface CWikiSubfolderStoryblok {
  title?: string;
  headline_type?: number | string;
  component: "c-wiki-subfolder";
  _uid: string;
  [k: string]: any;
}

export interface CWikiSuitableForStoryblok {
  title?: string;
  headline_type?: number | string;
  filter: number | string;
  component: "c-wiki-suitable-for";
  _uid: string;
  [k: string]: any;
}

export interface FooterColumnStoryblok {
  title: string;
  links?: MenuItemStoryblok[];
  component: "footer_column";
  _uid: string;
  [k: string]: any;
}

export interface MenuItemStoryblok {
  title: string;
  link: Exclude<MultilinkStoryblok, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "menu_item";
  _uid: string;
  [k: string]: any;
}

export interface TypeAppointmentStoryblok {
  title: string;
  description?: string;
  start_at: string;
  end_at: string;
  component: "type-appointment";
  _uid: string;
  [k: string]: any;
}

export interface TypeAppointmentOverviewStoryblok {
  component: "type-appointment-overview";
  _uid: string;
  [k: string]: any;
}

export interface TypeAuthorStoryblok {
  image: AssetStoryblok;
  notice?: string;
  description: string;
  email?: string;
  component: "type-author";
  _uid: string;
  [k: string]: any;
}

export interface TypeBlogStoryblok {
  toc?: boolean;
  additional_title?: string;
  title: string;
  published_date: string;
  author?: (ISbStoryData<TypeAuthorStoryblok> | string)[];
  image?: AssetStoryblok;
  categories?: (ISbStoryData<TypeBlogOverviewStoryblok> | string)[];
  tags?: ("" | "tech")[];
  body?: any[];
  component: "type-blog";
  _uid: string;
  [k: string]: any;
}

export interface TypeBlogOverviewStoryblok {
  newsletter_headline_type: number | string;
  newsletter_title?: string;
  newsletter_description?: string;
  additional_title?: string;
  title: string;
  image?: AssetStoryblok;
  mailing_list_id: string;
  newsletter_interests?: (number | string)[];
  component: "type-blog-overview";
  _uid: string;
  [k: string]: any;
}

export interface TypeCategoryStoryblok {
  body_top?: any[];
  body_bottom?: any[];
  component: "type-category";
  _uid: string;
  [k: string]: any;
}

export interface TypeFaqStoryblok {
  body: RichtextStoryblok;
  tags?: (number | string)[];
  visibility?: (number | string)[];
  component: "type-faq";
  _uid: string;
  [k: string]: any;
}

export interface TypeFaqOverviewStoryblok {
  title?: string;
  description?: RichtextStoryblok;
  visibility?: (number | string)[];
  component: "type-faq-overview";
  _uid: string;
  [k: string]: any;
}

export interface TypeLandingPageStoryblok {
  body?: any[];
  component: "type-landing-page";
  _uid: string;
  [k: string]: any;
}

export interface TypeManufacturerOverviewStoryblok {
  body?: any[];
  component: "type-manufacturer-overview";
  _uid: string;
  [k: string]: any;
}

export interface TypeManufacturerPageStoryblok {
  body_above?: any[];
  body_bottom?: any[];
  component: "type-manufacturer-page";
  _uid: string;
  [k: string]: any;
}

export interface TypePageStoryblok {
  body_top?: any[];
  body?: any[];
  component: "type-page";
  _uid: string;
  [k: string]: any;
}

export interface TypeProductStoryblok {
  body?: any[];
  component: "type-product";
  _uid: string;
  [k: string]: any;
}

export interface TypeWikiStoryblok {
  title: string;
  products_headline?: string;
  description: string;
  image: AssetStoryblok;
  datasheet?: AssetStoryblok;
  suitable_for: (number | string)[];
  visibility?: (number | string)[];
  component: "type-wiki";
  _uid: string;
  [k: string]: any;
}

export interface TypeWikiOverviewStoryblok {
  title: string;
  description?: RichtextStoryblok;
  image?: AssetStoryblok;
  body?: any[];
  visibility?: (number | string)[];
  component: "type-wiki-overview";
  _uid: string;
  [k: string]: any;
}

export interface UspEntryStoryblok {
  icon?: string;
  title: RichtextStoryblok;
  component: "usp_entry";
  _uid: string;
  [k: string]: any;
}
